// THIS SECTION IS A SET OF ARRAYS OF CHOICES 

export const classification = [
    'Book',
    'Special Problem',
    'Thesis'
  ]
  
export const course = [
  'CMSC 2 ',
  'CMSC 11',
  'CMSC 12',
  'CMSC 21',
  'CMSC 22',
  'CMSC 23',
  'CMSC 56',
  'CMSC 57',
  'CMSC 100',
  'CMSC 123',
  'CMSC 124',
  'CMSC 125',
  'CMSC 127',
  'CMSC 128',
  'CMSC 129',
  'CMSC 130',
  'CMSC 131',
  'CMSC 132',
  'CMSC 137',
  'CMSC 141',
  'CMSC 142',
  'CMSC 150',
  'CMSC 161',
  'CMSC 165',
  'CMSC 170',
  'CMSC 172',
  'CMSC 173',
  'CMSC 180',
  'CMSC 190',
  'CMSC 191',
  'CMSC 198',
  'CMSC 199',
  'CMSC 200'
]

export const topics = [
'Algorithms',
'Android Development',
'Artificial Intelligence',
'Automata',
'Bioinformatics',
'Computer Architecture',
'Computer Graphics',
'Computer Security',
'Cryptography',
'Data Structures',
'Database Management',
'Discrete Mathematics',
'Distributed Computing',
'Human-Computer Interaction',
'Image Processing',
'Machine Learning',
'Networking',
'Operating System',
'Parallel Algorithms',
'Programming Languages',
'Robotics',
'Security',
'Software Engineering',
'Special Topic',
'Speech Recognition',
'User Interface',
'Web Development',
]